W_SCALE = 55
D_SCALE = 15
WINDOWSIZE = (16 * W_SCALE, 9 * W_SCALE)
DISPLAYSIZE = (16 * D_SCALE, 9 * D_SCALE)
WD_DIF = W_SCALE / D_SCALE
FPS_CAP = 60

RENDER_SCALE = 30

SPHERE_RES = 4 # 10 is 27 * 8 points
